### ISSUE TITLE
how to use perform_action

### ISSUE THREAD

**Issue by shijunti19** [rkarp/winapi-easy#3]
perform_action(self, WindowHandle::WindowAction.Close)

**Comment by rkarp** [comment]
You could iterate over all toplevel windows as in the example [get_window_infos.rs](https://github.com/rkarp/winapi-easy/blob/747186e19a90a0c003f11a2348bd27906f599052/examples/get_window_infos.rs#L17-L19), filter any windows you like and then call `perform_action` on them.

**Comment by shijunti19** [comment]
@rkarp associated function `perform_action` is private
I want to close the specified window with one click


```rust
use std::io;
use winapi_easy::ui::{Rectangle, WindowHandle, WindowShowState};
#[derive(Debug)]
struct WindowInfo {
    caption: String,
    class_name: String,
    show_state: WindowShowState,
    restored_position: Rectangle,
}
pub fn run() -> io::Result<()> {
    WindowHandle::get_toplevel_windows()?
        .into_iter()
        .filter(|window| match window.get_class_name() {
            Ok(class_name) => class_name == "CabinetWClass",
            Err(_) => false,
        })
        .map(|window| {
            // window.perform_action();
            let placement = window.get_placement()?;
            Ok(WindowInfo {
                caption: window.get_caption_text(),
                class_name: window.get_class_name()?,
                show_state: placement.get_show_state().unwrap(),
                restored_position: placement.get_restored_position(),
            })
        });
    // .try_for_each(|info: io::Result<WindowInfo>| -> io::Result<()> {
    //     println!("{:#?}", info?);
    //     Ok(())
    // })?;
    Ok(())
}
```

**Comment by rkarp** [comment]
@shijunti19 
I remember now, this API wasn't quite ready yet since not all possible commands are implemented. But with non-exhaustive enums, it should be extensible. I've changed the names (e.g. `send_command`) and made the items public on `master`.
